#!/bin/bash

# recreate folder structure in local_archive folder

work=/home/jeremy/shares/server.z/_work/ul_archive


paths=( "$work/movies/after2011" 
		"$work/movies/animated" 
		"$work/movies/before2011" 
		"$work/movies/foreign" 
		"$work/movies/extras" 
		"$work/tv/archive" 
		"$work/tv/docs" 
		"$work/tv/reality" 
		"$work/tv/specials" 
		"$work/comics"
		"$work/personal"
		"$work/software"
		"$work/comics/DC/Batman"
		"$work/comics/DC/Green Arrow"
		"$work/comics/DC/Green Hornet"
		"$work/comics/DC/Justice League"
		"$work/comics/DC/Resurrection Man"
		"$work/comics/DC/Suicide Squad"
		"$work/comics/DC/Superboy"
		"$work/comics/DC/Superman"
		"$work/comics/DC/Superman/Superboy"
		"$work/comics/DC/The Outsiders"
		"$work/comics/DC/~Events"
		"$work/comics/DC/~Story Arcs"
		"$work/comics/DC/~Team-Ups"
		"$work/comics/Eclipse Comics"
		"$work/comics/Marvel/Avengers"
		"$work/comics/Marvel/Black Panther"
		"$work/comics/Marvel/Captain America"
		"$work/comics/Marvel/Captain Carrot"
		"$work/comics/Marvel/Captain Marvel"
		"$work/comics/Marvel/Doctor Strange"
		"$work/comics/Marvel/Fantastic Four"
		"$work/comics/Marvel/Fantastic Four/Annuals"
		"$work/comics/Marvel/Guardians of the Galaxy"
		"$work/comics/Marvel/Howard the Duck"
		"$work/comics/Marvel/Inhumans"
		"$work/comics/Marvel/Iron Man"
		"$work/comics/Marvel/Moon Knight"
		"$work/comics/Marvel/Nova"
		"$work/comics/Marvel/S.H.I.E.L.D"
		"$work/comics/Marvel/Silver Surfer"
		"$work/comics/Marvel/Spider-Woman"
		"$work/comics/Marvel/Star Trek"
		"$work/comics/Marvel/Star Trek/Star Trek (Marvel)"
		"$work/comics/Marvel/Star Trek/Star Trek (Marvel)/Star Trek (DC)"
		"$work/comics/Marvel/Star Wars"
		"$work/comics/Marvel/Sub-Mariner"
		"$work/comics/Marvel/Thor"
		"$work/comics/Marvel/Thor/Annuals"
		"$work/comics/Marvel/Thor/Journey Into Mystery"
		"$work/comics/Marvel/X-Men"
		"$work/comics/Marvel/~Events"
		"$work/comics/Marvel/~Story Arcs"
		"$work/comics/Marvel/~Team-Ups"	
)

for p in "${paths[@]}"; do 
	# echo "$p"
	mkdir --verbose -p "$p"
done

